<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $view \SebTech\FAQTwo\ViewModel\Question */

$view = $block->getData('question_view_model');
$questions = $view->getQuestions();
?>
<div id="question-view" data-bind="scope: 'question'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "#question-view": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "question": {
                        "component": "SebTech_FAQTwo/js/question",
                        "config": {
                            "questions": <?= json_encode($view->getQuestionsAsArray()) ?>
                        }
                    }
                }
            }
        }
    }
</script>


